// Generated by cpp11: do not edit by hand
// clang-format off

#include "aznyan_types.h"
#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// blur.cpp
cpp11::integers azny_medianblur(const cpp11::integers& nr, int height, int width, int ksize);
extern "C" SEXP _aznyan_azny_medianblur(SEXP nr, SEXP height, SEXP width, SEXP ksize) {
  BEGIN_CPP11
    return cpp11::as_sexp(azny_medianblur(cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(nr), cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<int>>(ksize)));
  END_CPP11
}
// blur.cpp
cpp11::integers azny_boxblur(const cpp11::integers& nr, int height, int width, int boxW, int boxH, bool normalize, int border);
extern "C" SEXP _aznyan_azny_boxblur(SEXP nr, SEXP height, SEXP width, SEXP boxW, SEXP boxH, SEXP normalize, SEXP border) {
  BEGIN_CPP11
    return cpp11::as_sexp(azny_boxblur(cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(nr), cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<int>>(boxW), cpp11::as_cpp<cpp11::decay_t<int>>(boxH), cpp11::as_cpp<cpp11::decay_t<bool>>(normalize), cpp11::as_cpp<cpp11::decay_t<int>>(border)));
  END_CPP11
}
// blur.cpp
cpp11::integers azny_gaussianblur(const cpp11::integers& nr, int height, int width, int boxW, int boxH, double sigmaX, double sigmaY, int border);
extern "C" SEXP _aznyan_azny_gaussianblur(SEXP nr, SEXP height, SEXP width, SEXP boxW, SEXP boxH, SEXP sigmaX, SEXP sigmaY, SEXP border) {
  BEGIN_CPP11
    return cpp11::as_sexp(azny_gaussianblur(cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(nr), cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<int>>(boxW), cpp11::as_cpp<cpp11::decay_t<int>>(boxH), cpp11::as_cpp<cpp11::decay_t<double>>(sigmaX), cpp11::as_cpp<cpp11::decay_t<double>>(sigmaY), cpp11::as_cpp<cpp11::decay_t<int>>(border)));
  END_CPP11
}
// blur.cpp
cpp11::integers azny_bilateralblur(const cpp11::integers& nr, int height, int width, int d, double sigmacolor, double sigmaspace, int border, bool alphasync);
extern "C" SEXP _aznyan_azny_bilateralblur(SEXP nr, SEXP height, SEXP width, SEXP d, SEXP sigmacolor, SEXP sigmaspace, SEXP border, SEXP alphasync) {
  BEGIN_CPP11
    return cpp11::as_sexp(azny_bilateralblur(cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(nr), cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<int>>(d), cpp11::as_cpp<cpp11::decay_t<double>>(sigmacolor), cpp11::as_cpp<cpp11::decay_t<double>>(sigmaspace), cpp11::as_cpp<cpp11::decay_t<int>>(border), cpp11::as_cpp<cpp11::decay_t<bool>>(alphasync)));
  END_CPP11
}
// blur.cpp
cpp11::integers azny_convolve(const cpp11::integers& nr, int height, int width, const cpp11::doubles_matrix<>& kernel, int border, bool alphasync);
extern "C" SEXP _aznyan_azny_convolve(SEXP nr, SEXP height, SEXP width, SEXP kernel, SEXP border, SEXP alphasync) {
  BEGIN_CPP11
    return cpp11::as_sexp(azny_convolve(cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(nr), cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<const cpp11::doubles_matrix<>&>>(kernel), cpp11::as_cpp<cpp11::decay_t<int>>(border), cpp11::as_cpp<cpp11::decay_t<bool>>(alphasync)));
  END_CPP11
}
// blurhash.cpp
cpp11::integers azny_blurhash(const cpp11::integers& nr, int height, int width, int x_comps, int y_comps);
extern "C" SEXP _aznyan_azny_blurhash(SEXP nr, SEXP height, SEXP width, SEXP x_comps, SEXP y_comps) {
  BEGIN_CPP11
    return cpp11::as_sexp(azny_blurhash(cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(nr), cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<int>>(x_comps), cpp11::as_cpp<cpp11::decay_t<int>>(y_comps)));
  END_CPP11
}
// color.cpp
cpp11::doubles azny_decode_rec709(const std::vector<double>& in_vec);
extern "C" SEXP _aznyan_azny_decode_rec709(SEXP in_vec) {
  BEGIN_CPP11
    return cpp11::as_sexp(azny_decode_rec709(cpp11::as_cpp<cpp11::decay_t<const std::vector<double>&>>(in_vec)));
  END_CPP11
}
// color.cpp
cpp11::doubles azny_encode_rec709(const std::vector<double>& in_vec);
extern "C" SEXP _aznyan_azny_encode_rec709(SEXP in_vec) {
  BEGIN_CPP11
    return cpp11::as_sexp(azny_encode_rec709(cpp11::as_cpp<cpp11::decay_t<const std::vector<double>&>>(in_vec)));
  END_CPP11
}
// color.cpp
cpp11::doubles azny_saturate_value(const cpp11::doubles& in_vec, double val);
extern "C" SEXP _aznyan_azny_saturate_value(SEXP in_vec, SEXP val) {
  BEGIN_CPP11
    return cpp11::as_sexp(azny_saturate_value(cpp11::as_cpp<cpp11::decay_t<const cpp11::doubles&>>(in_vec), cpp11::as_cpp<cpp11::decay_t<double>>(val)));
  END_CPP11
}
// color.cpp
cpp11::integers azny_pack_integers(const cpp11::doubles_matrix<>& rgb, const cpp11::doubles& a, int height, int width);
extern "C" SEXP _aznyan_azny_pack_integers(SEXP rgb, SEXP a, SEXP height, SEXP width) {
  BEGIN_CPP11
    return cpp11::as_sexp(azny_pack_integers(cpp11::as_cpp<cpp11::decay_t<const cpp11::doubles_matrix<>&>>(rgb), cpp11::as_cpp<cpp11::decay_t<const cpp11::doubles&>>(a), cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<int>>(width)));
  END_CPP11
}
// color.cpp
cpp11::integers azny_unpack_integers(const cpp11::integers& nr);
extern "C" SEXP _aznyan_azny_unpack_integers(SEXP nr) {
  BEGIN_CPP11
    return cpp11::as_sexp(azny_unpack_integers(cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(nr)));
  END_CPP11
}
// color.cpp
cpp11::integers azny_rgb_to_hls(const cpp11::integers_matrix<>& rgb);
extern "C" SEXP _aznyan_azny_rgb_to_hls(SEXP rgb) {
  BEGIN_CPP11
    return cpp11::as_sexp(azny_rgb_to_hls(cpp11::as_cpp<cpp11::decay_t<const cpp11::integers_matrix<>&>>(rgb)));
  END_CPP11
}
// color.cpp
cpp11::integers azny_hls_to_rgb(const cpp11::integers_matrix<>& hls);
extern "C" SEXP _aznyan_azny_hls_to_rgb(SEXP hls) {
  BEGIN_CPP11
    return cpp11::as_sexp(azny_hls_to_rgb(cpp11::as_cpp<cpp11::decay_t<const cpp11::integers_matrix<>&>>(hls)));
  END_CPP11
}
// color.cpp
cpp11::integers azny_color_map(const cpp11::integers& nr, int height, int width, int mode, bool hsvmode, bool invmode);
extern "C" SEXP _aznyan_azny_color_map(SEXP nr, SEXP height, SEXP width, SEXP mode, SEXP hsvmode, SEXP invmode) {
  BEGIN_CPP11
    return cpp11::as_sexp(azny_color_map(cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(nr), cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<int>>(mode), cpp11::as_cpp<cpp11::decay_t<bool>>(hsvmode), cpp11::as_cpp<cpp11::decay_t<bool>>(invmode)));
  END_CPP11
}
// diffusion.cpp
cpp11::integers azny_diffusion(const cpp11::integers& nr, int height, int width, int iter, float decay_factor, float decay_offset, float gamma, int sigma);
extern "C" SEXP _aznyan_azny_diffusion(SEXP nr, SEXP height, SEXP width, SEXP iter, SEXP decay_factor, SEXP decay_offset, SEXP gamma, SEXP sigma) {
  BEGIN_CPP11
    return cpp11::as_sexp(azny_diffusion(cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(nr), cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<int>>(iter), cpp11::as_cpp<cpp11::decay_t<float>>(decay_factor), cpp11::as_cpp<cpp11::decay_t<float>>(decay_offset), cpp11::as_cpp<cpp11::decay_t<float>>(gamma), cpp11::as_cpp<cpp11::decay_t<int>>(sigma)));
  END_CPP11
}
// edge-canny.cpp
cpp11::integers azny_cannyfilter(const cpp11::integers& nr, int height, int width, int asize, bool balp, bool gradient, double thres1, double thres2);
extern "C" SEXP _aznyan_azny_cannyfilter(SEXP nr, SEXP height, SEXP width, SEXP asize, SEXP balp, SEXP gradient, SEXP thres1, SEXP thres2) {
  BEGIN_CPP11
    return cpp11::as_sexp(azny_cannyfilter(cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(nr), cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<int>>(asize), cpp11::as_cpp<cpp11::decay_t<bool>>(balp), cpp11::as_cpp<cpp11::decay_t<bool>>(gradient), cpp11::as_cpp<cpp11::decay_t<double>>(thres1), cpp11::as_cpp<cpp11::decay_t<double>>(thres2)));
  END_CPP11
}
// edge-canny.cpp
cpp11::integers azny_cannyrgb(const cpp11::integers& nr, int height, int width, int asize, bool balp, bool gradient, double thres1, double thres2);
extern "C" SEXP _aznyan_azny_cannyrgb(SEXP nr, SEXP height, SEXP width, SEXP asize, SEXP balp, SEXP gradient, SEXP thres1, SEXP thres2) {
  BEGIN_CPP11
    return cpp11::as_sexp(azny_cannyrgb(cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(nr), cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<int>>(asize), cpp11::as_cpp<cpp11::decay_t<bool>>(balp), cpp11::as_cpp<cpp11::decay_t<bool>>(gradient), cpp11::as_cpp<cpp11::decay_t<double>>(thres1), cpp11::as_cpp<cpp11::decay_t<double>>(thres2)));
  END_CPP11
}
// edge-laplacian.cpp
cpp11::integers azny_laplacianfilter(const cpp11::integers& nr, int height, int width, int ksize, bool balp, int border, double scale, double delta);
extern "C" SEXP _aznyan_azny_laplacianfilter(SEXP nr, SEXP height, SEXP width, SEXP ksize, SEXP balp, SEXP border, SEXP scale, SEXP delta) {
  BEGIN_CPP11
    return cpp11::as_sexp(azny_laplacianfilter(cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(nr), cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<int>>(ksize), cpp11::as_cpp<cpp11::decay_t<bool>>(balp), cpp11::as_cpp<cpp11::decay_t<int>>(border), cpp11::as_cpp<cpp11::decay_t<double>>(scale), cpp11::as_cpp<cpp11::decay_t<double>>(delta)));
  END_CPP11
}
// edge-laplacian.cpp
cpp11::integers azny_laplacianrgb(const cpp11::integers& nr, int height, int width, int ksize, bool balp, int border, double scale, double delta);
extern "C" SEXP _aznyan_azny_laplacianrgb(SEXP nr, SEXP height, SEXP width, SEXP ksize, SEXP balp, SEXP border, SEXP scale, SEXP delta) {
  BEGIN_CPP11
    return cpp11::as_sexp(azny_laplacianrgb(cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(nr), cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<int>>(ksize), cpp11::as_cpp<cpp11::decay_t<bool>>(balp), cpp11::as_cpp<cpp11::decay_t<int>>(border), cpp11::as_cpp<cpp11::decay_t<double>>(scale), cpp11::as_cpp<cpp11::decay_t<double>>(delta)));
  END_CPP11
}
// edge-sobel.cpp
cpp11::integers azny_sobelfilter(const cpp11::integers& nr, int height, int width, int ksize, bool balp, int dx, int dy, int border, double scale, double delta);
extern "C" SEXP _aznyan_azny_sobelfilter(SEXP nr, SEXP height, SEXP width, SEXP ksize, SEXP balp, SEXP dx, SEXP dy, SEXP border, SEXP scale, SEXP delta) {
  BEGIN_CPP11
    return cpp11::as_sexp(azny_sobelfilter(cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(nr), cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<int>>(ksize), cpp11::as_cpp<cpp11::decay_t<bool>>(balp), cpp11::as_cpp<cpp11::decay_t<int>>(dx), cpp11::as_cpp<cpp11::decay_t<int>>(dy), cpp11::as_cpp<cpp11::decay_t<int>>(border), cpp11::as_cpp<cpp11::decay_t<double>>(scale), cpp11::as_cpp<cpp11::decay_t<double>>(delta)));
  END_CPP11
}
// edge-sobel.cpp
cpp11::integers azny_sobelrgb(const cpp11::integers& nr, int height, int width, int ksize, bool balp, int dx, int dy, int border, double scale, double delta);
extern "C" SEXP _aznyan_azny_sobelrgb(SEXP nr, SEXP height, SEXP width, SEXP ksize, SEXP balp, SEXP dx, SEXP dy, SEXP border, SEXP scale, SEXP delta) {
  BEGIN_CPP11
    return cpp11::as_sexp(azny_sobelrgb(cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(nr), cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<int>>(ksize), cpp11::as_cpp<cpp11::decay_t<bool>>(balp), cpp11::as_cpp<cpp11::decay_t<int>>(dx), cpp11::as_cpp<cpp11::decay_t<int>>(dy), cpp11::as_cpp<cpp11::decay_t<int>>(border), cpp11::as_cpp<cpp11::decay_t<double>>(scale), cpp11::as_cpp<cpp11::decay_t<double>>(delta)));
  END_CPP11
}
// misc.cpp
cpp11::integers azny_swap_channels(const cpp11::integers& nr, int height, int width, const std::vector<int>& mapping);
extern "C" SEXP _aznyan_azny_swap_channels(SEXP nr, SEXP height, SEXP width, SEXP mapping) {
  BEGIN_CPP11
    return cpp11::as_sexp(azny_swap_channels(cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(nr), cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<const std::vector<int>&>>(mapping)));
  END_CPP11
}
// misc.cpp
cpp11::integers azny_resize(const cpp11::integers& nr, int height, int width, cpp11::doubles wh, int resize_mode, bool set_size);
extern "C" SEXP _aznyan_azny_resize(SEXP nr, SEXP height, SEXP width, SEXP wh, SEXP resize_mode, SEXP set_size) {
  BEGIN_CPP11
    return cpp11::as_sexp(azny_resize(cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(nr), cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(wh), cpp11::as_cpp<cpp11::decay_t<int>>(resize_mode), cpp11::as_cpp<cpp11::decay_t<bool>>(set_size)));
  END_CPP11
}
// misc.cpp
cpp11::integers azny_resample(const cpp11::integers& nr, int height, int width, cpp11::doubles wh, int resize_red, int resize_exp);
extern "C" SEXP _aznyan_azny_resample(SEXP nr, SEXP height, SEXP width, SEXP wh, SEXP resize_red, SEXP resize_exp) {
  BEGIN_CPP11
    return cpp11::as_sexp(azny_resample(cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(nr), cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(wh), cpp11::as_cpp<cpp11::decay_t<int>>(resize_red), cpp11::as_cpp<cpp11::decay_t<int>>(resize_exp)));
  END_CPP11
}
// misc.cpp
int get_num_threads();
extern "C" SEXP _aznyan_get_num_threads() {
  BEGIN_CPP11
    return cpp11::as_sexp(get_num_threads());
  END_CPP11
}
// morph.cpp
cpp11::integers azny_morphologyfilter(const cpp11::integers& nr, int height, int width, int ksize, int ktype, int mode, int iterations, int border, bool alphasync, cpp11::integers pt);
extern "C" SEXP _aznyan_azny_morphologyfilter(SEXP nr, SEXP height, SEXP width, SEXP ksize, SEXP ktype, SEXP mode, SEXP iterations, SEXP border, SEXP alphasync, SEXP pt) {
  BEGIN_CPP11
    return cpp11::as_sexp(azny_morphologyfilter(cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(nr), cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<int>>(ksize), cpp11::as_cpp<cpp11::decay_t<int>>(ktype), cpp11::as_cpp<cpp11::decay_t<int>>(mode), cpp11::as_cpp<cpp11::decay_t<int>>(iterations), cpp11::as_cpp<cpp11::decay_t<int>>(border), cpp11::as_cpp<cpp11::decay_t<bool>>(alphasync), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(pt)));
  END_CPP11
}
// morph.cpp
cpp11::integers azny_morphologyrgb(const cpp11::integers& nr, int height, int width, cpp11::integers ksize, int ktype, int mode, int iterations, int border, bool alphasync, cpp11::integers pt);
extern "C" SEXP _aznyan_azny_morphologyrgb(SEXP nr, SEXP height, SEXP width, SEXP ksize, SEXP ktype, SEXP mode, SEXP iterations, SEXP border, SEXP alphasync, SEXP pt) {
  BEGIN_CPP11
    return cpp11::as_sexp(azny_morphologyrgb(cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(nr), cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(ksize), cpp11::as_cpp<cpp11::decay_t<int>>(ktype), cpp11::as_cpp<cpp11::decay_t<int>>(mode), cpp11::as_cpp<cpp11::decay_t<int>>(iterations), cpp11::as_cpp<cpp11::decay_t<int>>(border), cpp11::as_cpp<cpp11::decay_t<bool>>(alphasync), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(pt)));
  END_CPP11
}
// others.cpp
cpp11::integers azny_meanshift(const cpp11::integers& nr, int height, int width, double sp, double sr, int maxl);
extern "C" SEXP _aznyan_azny_meanshift(SEXP nr, SEXP height, SEXP width, SEXP sp, SEXP sr, SEXP maxl) {
  BEGIN_CPP11
    return cpp11::as_sexp(azny_meanshift(cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(nr), cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<double>>(sp), cpp11::as_cpp<cpp11::decay_t<double>>(sr), cpp11::as_cpp<cpp11::decay_t<int>>(maxl)));
  END_CPP11
}
// others.cpp
cpp11::integers azny_preserve_edges(const cpp11::integers& nr, int height, int width, float sgmS, float sgmR, bool mode);
extern "C" SEXP _aznyan_azny_preserve_edges(SEXP nr, SEXP height, SEXP width, SEXP sgmS, SEXP sgmR, SEXP mode) {
  BEGIN_CPP11
    return cpp11::as_sexp(azny_preserve_edges(cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(nr), cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<float>>(sgmS), cpp11::as_cpp<cpp11::decay_t<float>>(sgmR), cpp11::as_cpp<cpp11::decay_t<bool>>(mode)));
  END_CPP11
}
// threshold.cpp
cpp11::integers azny_thres(const cpp11::integers& nr, int height, int width, double thres, double maxv, int mode);
extern "C" SEXP _aznyan_azny_thres(SEXP nr, SEXP height, SEXP width, SEXP thres, SEXP maxv, SEXP mode) {
  BEGIN_CPP11
    return cpp11::as_sexp(azny_thres(cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(nr), cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<double>>(thres), cpp11::as_cpp<cpp11::decay_t<double>>(maxv), cpp11::as_cpp<cpp11::decay_t<int>>(mode)));
  END_CPP11
}
// threshold.cpp
cpp11::integers azny_adpthres(const cpp11::integers& nr, int height, int width, bool adpthres, double maxv, int bsize, bool mode, double valC);
extern "C" SEXP _aznyan_azny_adpthres(SEXP nr, SEXP height, SEXP width, SEXP adpthres, SEXP maxv, SEXP bsize, SEXP mode, SEXP valC) {
  BEGIN_CPP11
    return cpp11::as_sexp(azny_adpthres(cpp11::as_cpp<cpp11::decay_t<const cpp11::integers&>>(nr), cpp11::as_cpp<cpp11::decay_t<int>>(height), cpp11::as_cpp<cpp11::decay_t<int>>(width), cpp11::as_cpp<cpp11::decay_t<bool>>(adpthres), cpp11::as_cpp<cpp11::decay_t<double>>(maxv), cpp11::as_cpp<cpp11::decay_t<int>>(bsize), cpp11::as_cpp<cpp11::decay_t<bool>>(mode), cpp11::as_cpp<cpp11::decay_t<double>>(valC)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_aznyan_azny_adpthres",         (DL_FUNC) &_aznyan_azny_adpthres,          8},
    {"_aznyan_azny_bilateralblur",    (DL_FUNC) &_aznyan_azny_bilateralblur,     8},
    {"_aznyan_azny_blurhash",         (DL_FUNC) &_aznyan_azny_blurhash,          5},
    {"_aznyan_azny_boxblur",          (DL_FUNC) &_aznyan_azny_boxblur,           7},
    {"_aznyan_azny_cannyfilter",      (DL_FUNC) &_aznyan_azny_cannyfilter,       8},
    {"_aznyan_azny_cannyrgb",         (DL_FUNC) &_aznyan_azny_cannyrgb,          8},
    {"_aznyan_azny_color_map",        (DL_FUNC) &_aznyan_azny_color_map,         6},
    {"_aznyan_azny_convolve",         (DL_FUNC) &_aznyan_azny_convolve,          6},
    {"_aznyan_azny_decode_rec709",    (DL_FUNC) &_aznyan_azny_decode_rec709,     1},
    {"_aznyan_azny_diffusion",        (DL_FUNC) &_aznyan_azny_diffusion,         8},
    {"_aznyan_azny_encode_rec709",    (DL_FUNC) &_aznyan_azny_encode_rec709,     1},
    {"_aznyan_azny_gaussianblur",     (DL_FUNC) &_aznyan_azny_gaussianblur,      8},
    {"_aznyan_azny_hls_to_rgb",       (DL_FUNC) &_aznyan_azny_hls_to_rgb,        1},
    {"_aznyan_azny_laplacianfilter",  (DL_FUNC) &_aznyan_azny_laplacianfilter,   8},
    {"_aznyan_azny_laplacianrgb",     (DL_FUNC) &_aznyan_azny_laplacianrgb,      8},
    {"_aznyan_azny_meanshift",        (DL_FUNC) &_aznyan_azny_meanshift,         6},
    {"_aznyan_azny_medianblur",       (DL_FUNC) &_aznyan_azny_medianblur,        4},
    {"_aznyan_azny_morphologyfilter", (DL_FUNC) &_aznyan_azny_morphologyfilter, 10},
    {"_aznyan_azny_morphologyrgb",    (DL_FUNC) &_aznyan_azny_morphologyrgb,    10},
    {"_aznyan_azny_pack_integers",    (DL_FUNC) &_aznyan_azny_pack_integers,     4},
    {"_aznyan_azny_preserve_edges",   (DL_FUNC) &_aznyan_azny_preserve_edges,    6},
    {"_aznyan_azny_resample",         (DL_FUNC) &_aznyan_azny_resample,          6},
    {"_aznyan_azny_resize",           (DL_FUNC) &_aznyan_azny_resize,            6},
    {"_aznyan_azny_rgb_to_hls",       (DL_FUNC) &_aznyan_azny_rgb_to_hls,        1},
    {"_aznyan_azny_saturate_value",   (DL_FUNC) &_aznyan_azny_saturate_value,    2},
    {"_aznyan_azny_sobelfilter",      (DL_FUNC) &_aznyan_azny_sobelfilter,      10},
    {"_aznyan_azny_sobelrgb",         (DL_FUNC) &_aznyan_azny_sobelrgb,         10},
    {"_aznyan_azny_swap_channels",    (DL_FUNC) &_aznyan_azny_swap_channels,     4},
    {"_aznyan_azny_thres",            (DL_FUNC) &_aznyan_azny_thres,             6},
    {"_aznyan_azny_unpack_integers",  (DL_FUNC) &_aznyan_azny_unpack_integers,   1},
    {"_aznyan_get_num_threads",       (DL_FUNC) &_aznyan_get_num_threads,        0},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_aznyan(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
