# Generated by cpp11: do not edit by hand

azny_medianblur <- function(png, ksize) {
  .Call(`_aznyan_azny_medianblur`, png, ksize)
}

azny_boxblur <- function(png, box_w, box_h, normalize, border) {
  .Call(`_aznyan_azny_boxblur`, png, box_w, box_h, normalize, border)
}

azny_gaussianblur <- function(png, box_w, box_h, sigma_x, sigma_y, border) {
  .Call(`_aznyan_azny_gaussianblur`, png, box_w, box_h, sigma_x, sigma_y, border)
}
